### PR TITLE
Create en-GB.override.ini

### PR DESCRIPTION
**Pull request by particthistle**
Preliminary list to address #18 and convert references to "blog", "post", "bloggers" etc to corresponding terms for "magazine articles", "articles" and "authors" etc as appropriate.

Initial list is not exhaustive, but covers majority of public facing and author facing front end language strings I've been able to identify. @jeckodevelopment you might have already got a list started with more of these.

This may be an experiment to try for CrowdIn @conconnl? I've not used it enough yet to know whether you can upload en-GB.override.ini into a project and then from there have that file translated into other languages.

### CODE REVIEW

**Comment by conconnl** [comment]
What would be the reason to translate it?
The site doesn’t have any related to other languages in the system. 

The PR needs to hold the existing overrides else things will break.

**Comment by conconnl** [comment]
Which are, not sure for what they are used.

COM_EASYBLOG_DASHBOARD_HEADING_POSTS="Articles"
COM_EASYBLOG_TEAMBLOG_TOTAL_POSTS="Articles"
COM_EASYBLOG_TEAMBLOGS_POSTS="Articles"
COM_EASYBLOG_SEARCH_BLOGGERS="Search Authors"
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT="By signing up to this web site and agreeing to the Privacy Policy you agree to this web site storing your information. </br>\nThe Privacy Policy can be found <a class=\"alert-link\" href=\"https://www.joomla.org/privacy-policy.html\" target=\"_blank\">here</a>."
ACYM_I_AGREE_PRIVACY="I consent to The Joomla Project to collect, process, store and use my personal data in connection with the receipt by email of the Joomla Newsletter.<br />Read the <a href=\"https://www.joomla.org/privacy-policy.html\" target=\"_blank\" rel=\"noopener\">Privacy Policy</a>"
COM_EASYBLOG_CATEGORIES_SUBCATEGORIES="Issues:"
COM_EASYBLOG_RECENT_NEWS="Latest Issue"
COM_EASYBLOG_HOME_CATEGORIES="Issues"
ACCEPT_TERMS="Your consent is required if you want to receive our newsletters."
AUTHOR_RESOURCES="Author Resources"
ARTICLE_SUBMISSION_BUCKET="Article Submission Bucket"
AUTHOR_LICENSE_AGREEMENT="AUTHOR LICENSE AGREEMENT"
TAGGED_UNDER="Tagged under"
READ_MORE...="Read more..."
REGISTER_REQUIRED="Fields marked with an asterisk (*) are required."
COM_EASYBLOG_TOOLBAR_CATEGORIES="Issues"

**Comment by particthistle** [comment]
@conconnl I've added those strings in now and then sorted the file alphabetically by constants to make finding and adding strings easier for the future.

I'm not sure that **READ_MORE...="Read more..."** is correct, as I couldn't find that string in my Easyblog install.

COM_EASYBLOG_READ_MORE="Read more" is the current setting.

Magazine is using COM_EASYBLOG_CONTINUE_READING="Continue reading" currently, so this one might be redundant if no one can find the READ_MORE... constant.

**Comment by particthistle** [comment]
> What would be the reason to translate it?
> The site doesn’t have any related to other languages in the system.

As discussed in Glip, further translation is not required at the moment.

**Comment by conconnl** [comment]
> I'm not sure that **READ_MORE...="Read more..."** is correct, as I couldn't find that string in my Easyblog install.
> 
I have no clue, I didn't build the website and if it's not in the CMS Language files, it's probably an error.

Do I need to merge this and put it on the server?

**Comment by particthistle** [comment]
The read more one was in the list you gave me of existing overrides.

Now that the suggested and existing overrides have all been combined into the one list in this PR you can merge this without loosing existing overrides.

**Pull request merged**
